obj-y   := ipq807x.o
obj-y	+= clock.o
obj-$(CONFIG_BUFFALO_WXR5950AX12) += wxr5950ax12.o
obj-$(CONFIG_BUFFALO_WXR5950AX12) += wxr5950ax12_boot.o
obj-$(CONFIG_BUFFALO_WXR5950AX12) += wxr5950ax12_nandboot.o
obj-$(CONFIG_BUFFALO_WXR5950AX12) += wxr5950ax12_usbboot.o
obj-$(CONFIG_BUFFALO_WXR5950AX12) += wxr5950ax12_ui.o
